# Generated by Django 4.1.4 on 2023-02-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelFieldMapper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "AppName",
                    models.CharField(
                        help_text="Name of the application which fields are to be mapped or FK established",
                        max_length=100,
                    ),
                ),
                (
                    "ModelName",
                    models.CharField(
                        help_text="Name of the model which fields are to be mapped",
                        max_length=100,
                    ),
                ),
                (
                    "ModelFieldName",
                    models.CharField(
                        help_text="Name of the model field to which the field needs to be mapped",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "ModelMappedName",
                    models.CharField(
                        help_text="Name of the mapped Model Field which needs to be mapped back to the field name",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "AppForeignKeyName",
                    models.CharField(
                        help_text="Name of the model field to which the field needs to be mapped",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "ModelForeignKeyModel",
                    models.CharField(
                        help_text="Name of the foreign model to use",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "ModelForeignKeyField",
                    models.CharField(
                        help_text="Name of the Field of the foreign model to use",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("ModelDoNotExport", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddConstraint(
            model_name="modelfieldmapper",
            constraint=models.UniqueConstraint(
                fields=("AppName", "ModelName", "ModelFieldName"), name="unique_Field"
            ),
        ),
    ]
