# Generated by Django 4.1.4 on 2023-02-14 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "AddressType",
                    models.CharField(
                        choices=[
                            ("MainResidentialAddress", "Residential address of Person"),
                            ("BoxMainAccessPlace", "Place where the boxes are located"),
                            ("AddressOfHeadquarters", "Addess of headquarter"),
                            ("Other", "Other type of address"),
                        ],
                        default="BoxMainAccessPlace",
                        max_length=40,
                    ),
                ),
                ("SequenceNumber", models.IntegerField()),
                ("Street", models.CharField(help_text="Street :", max_length=256)),
                (
                    "HouseNumber",
                    models.CharField(help_text="House number :", max_length=10),
                ),
                (
                    "PostBoxNumber",
                    models.CharField(help_text="Post Box Number :", max_length=40),
                ),
                (
                    "AdditionalAddressLine",
                    models.CharField(
                        help_text="Additional Address Line :", max_length=60
                    ),
                ),
                (
                    "PostalCode",
                    models.CharField(help_text="Postal Code:", max_length=10),
                ),
                ("City", models.CharField(help_text="City:", max_length=256)),
                ("Region", models.CharField(help_text="Postal Code:", max_length=20)),
                (
                    "Latitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Latitude (parallel to equator):",
                        max_digits=9,
                    ),
                ),
                (
                    "Longitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Longitude (Through Nord and south Pole)):",
                        max_digits=9,
                    ),
                ),
            ],
            options={"ordering": ["Country", "City", "Street"],},
        ),
        migrations.CreateModel(
            name="GeographicalUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "GeographicalUnitId",
                    models.CharField(help_text="Political Unit:", max_length=15),
                ),
                (
                    "GeographicalUnitCategory",
                    models.CharField(
                        choices=[
                            ("Continent", "Continent"),
                            ("Sea", "Sea"),
                            ("Ocean", "Ocean"),
                            ("Country", "Country"),
                            ("State", "State"),
                            ("City", "City"),
                            ("Commune", "Commune"),
                        ],
                        max_length=15,
                    ),
                ),
                ("GeographicalUnitName", models.CharField(max_length=100)),
                ("GeographicalUnitShortName", models.CharField(max_length=100)),
                ("HierarchyLevel", models.IntegerField(default=0)),
                (
                    "IsPartOf",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select a the geographical Unit it belogs to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="composition",
                        to="locations.geographicalunit",
                    ),
                ),
            ],
            options={
                "permissions": [("can_manage_locations", "Can manage locations")],
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "geographicalunit_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="locations.geographicalunit",
                    ),
                ),
                (
                    "CityCode",
                    models.CharField(help_text="Code for city :", max_length=100),
                ),
            ],
            bases=("locations.geographicalunit",),
        ),
        migrations.CreateModel(
            name="Continent",
            fields=[
                (
                    "geographicalunit_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="locations.geographicalunit",
                    ),
                ),
                (
                    "ContinentCode",
                    models.CharField(help_text="Code for Continent :", max_length=2),
                ),
            ],
            bases=("locations.geographicalunit",),
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "geographicalunit_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="locations.geographicalunit",
                    ),
                ),
                (
                    "CountryCode",
                    models.CharField(help_text="Iso2 Code for country :", max_length=2),
                ),
                (
                    "ISO3CountryCode",
                    models.CharField(help_text="Iso3 Code for Country :", max_length=3),
                ),
                (
                    "PhonePrefix",
                    models.CharField(
                        blank=True,
                        help_text="Phone Code for Country :",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "InternetSuffix",
                    models.CharField(
                        blank=True,
                        help_text="Internet suffix Code for Country with dot (example .fr) :",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "ISO3166Country",
                    models.CharField(
                        help_text="Iso316 Code for Country :", max_length=3, null=True
                    ),
                ),
            ],
            bases=("locations.geographicalunit",),
        ),
        migrations.AddConstraint(
            model_name="geographicalunit",
            constraint=models.UniqueConstraint(
                fields=("IsPartOf", "GeographicalUnitId"),
                name="locations_geographicalunit_unique_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="geographicalunit",
            constraint=models.UniqueConstraint(
                fields=("IsPartOf", "GeographicalUnitName"),
                name="locations_geographicalunit_unique_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="geographicalunit",
            constraint=models.UniqueConstraint(
                fields=("IsPartOf", "GeographicalUnitShortName"),
                name="locations_geographicalunit_unique_short_name",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="Country",
            field=models.ForeignKey(
                blank=True,
                help_text="Select a country:",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="locations.country",
            ),
        ),
    ]
