# Generated by Django 4.1.4 on 2023-02-15 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geographicalunit",
            name="GeographicalUnitCategory",
            field=models.CharField(
                choices=[
                    ("Planet", "Planet"),
                    ("Continent", "Continent"),
                    ("Sea", "Sea"),
                    ("Ocean", "Ocean"),
                    ("Country", "Country"),
                    ("State", "State"),
                    ("City", "City"),
                    ("Commune", "Commune"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="geographicalunit",
            name="IsPartOf",
            field=models.ForeignKey(
                blank=True,
                help_text="Select a the geographical Unit it belogs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="locations.geographicalunit",
            ),
        ),
    ]
