# Generated by Django 4.1.2 on 2023-02-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0003_alter_address_latitude_alter_address_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="AdditionalAddressLine",
            field=models.CharField(
                blank=True, help_text="Additional Address Line :", max_length=60
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="PostBoxNumber",
            field=models.CharField(
                blank=True, help_text="Post Box Number :", max_length=40
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="Region",
            field=models.CharField(help_text="Postal Code:", max_length=20, null=True),
        ),
    ]
