# Generated by Django 4.1.2 on 2023-02-23 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0005_alter_address_latitude_alter_address_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="City",
            field=models.CharField(
                blank=True, help_text="City:", max_length=256, null=True
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="Country",
            field=models.ForeignKey(
                blank=True,
                help_text="Enter a country:",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="locations.country",
            ),
        ),
    ]
