# Generated by Django 4.1.2 on 2023-02-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0006_alter_address_city_alter_address_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="geographicalunit",
            name="EntryStatus",
            field=models.CharField(
                choices=[
                    ("T", "Geo Location can change"),
                    ("D", "Geo Location Official"),
                ],
                default="D",
                max_length=15,
            ),
        ),
    ]
