# Generated by Django 4.1.4 on 2023-03-02 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("locations", "0007_geographicalunit_entrystatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="AccessCodes",
            field=models.CharField(
                blank=True, help_text="AccessCodes:", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="AddressCategory",
            field=models.CharField(
                choices=[
                    ("Address", "Address as managed by postal service"),
                    ("box", "Place of a box in an address"),
                ],
                default="UnSpecified",
                help_text="Enter selection:",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="AddressId",
            field=models.CharField(
                default="",
                help_text="Unique visible number location",
                max_length=128,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="EntryStatus",
            field=models.CharField(
                choices=[
                    ("T", "Geo Location can change"),
                    ("D", "Geo Location Official"),
                ],
                default="D",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="created_by",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addressCreated_by",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="address",
            name="updated_by",
            field=models.ForeignKey(
                default="aaa",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="address",
            name="AddressType",
            field=models.CharField(
                choices=[
                    ("UnSpecified", "The type of address is not specified"),
                    ("MainResidentialAddress", "Residential address of Person"),
                    ("BoxMainAccessPlace", "Place where the boxes are located"),
                    ("AddressOfHeadquarters", "Addess of headquarter"),
                    ("Other", "Other type of address"),
                ],
                default="UnSpecified",
                help_text="Enter selection:",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="SequenceNumber",
            field=models.IntegerField(help_text="address sequence number"),
        ),
        migrations.CreateModel(
            name="LivingUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "AddressId",
                    models.CharField(
                        help_text="Unique visible number location",
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "SequenceNumber",
                    models.IntegerField(help_text="address sequence number"),
                ),
                (
                    "AddressCategory",
                    models.CharField(
                        choices=[
                            ("Address", "Address as managed by postal service"),
                            ("box", "Place of a box in an address"),
                        ],
                        default="UnSpecified",
                        help_text="Enter selection:",
                        max_length=40,
                    ),
                ),
                (
                    "AccessCodes",
                    models.CharField(
                        blank=True, help_text="AccessCodes:", max_length=100, null=True
                    ),
                ),
                (
                    "EntryStatus",
                    models.CharField(
                        choices=[
                            ("T", "Geo Location can change"),
                            ("D", "Geo Location Official"),
                        ],
                        default="D",
                        max_length=15,
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "Building",
                    models.CharField(
                        blank=True, help_text="Building:", max_length=40, null=True
                    ),
                ),
                (
                    "Floor",
                    models.CharField(
                        blank=True, help_text="Floor:", max_length=20, null=True
                    ),
                ),
                (
                    "AppartmentReference",
                    models.CharField(
                        blank=True,
                        help_text="Appartment Reference:",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("AppartmentDescription", models.TextField()),
                (
                    "IsPartOf",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select ",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="locations.address",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="livingUnitCreated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Box",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "AddressId",
                    models.CharField(
                        help_text="Unique visible number location",
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "SequenceNumber",
                    models.IntegerField(help_text="address sequence number"),
                ),
                (
                    "AddressCategory",
                    models.CharField(
                        choices=[
                            ("Address", "Address as managed by postal service"),
                            ("box", "Place of a box in an address"),
                        ],
                        default="UnSpecified",
                        help_text="Enter selection:",
                        max_length=40,
                    ),
                ),
                (
                    "AccessCodes",
                    models.CharField(
                        blank=True, help_text="AccessCodes:", max_length=100, null=True
                    ),
                ),
                (
                    "EntryStatus",
                    models.CharField(
                        choices=[
                            ("T", "Geo Location can change"),
                            ("D", "Geo Location Official"),
                        ],
                        default="D",
                        max_length=15,
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "BoxReference",
                    models.CharField(
                        blank=True, help_text="BoxReference:", max_length=100, null=True
                    ),
                ),
                (
                    "BoxDepth",
                    models.DecimalField(
                        decimal_places=2, help_text="The depth of the box", max_digits=8
                    ),
                ),
                (
                    "BoxEntryWidth",
                    models.DecimalField(
                        decimal_places=2, help_text="The width of the box", max_digits=8
                    ),
                ),
                (
                    "BoxEntryHeight",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The height of the box",
                        max_digits=8,
                    ),
                ),
                ("BoxDescription", models.TextField()),
                (
                    "IsPartOf",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select ",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="locations.address",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boxCreated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
