# Generated by Django 4.1.4 on 2023-02-14 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "AssetId",
                    models.CharField(help_text="Identifies the asset:", max_length=20),
                ),
                (
                    "CompletionState",
                    models.CharField(
                        choices=[
                            ("ReadyForUse", "Ready for use"),
                            ("ReadyForOperation", "Ready for Operation"),
                            ("ReadyForRent", "Ready for Rent"),
                            ("ReadyForSale", "Ready for Sale"),
                            ("InConstruction", "In Construction"),
                            ("Removed", "Removed, not used anymore"),
                            ("In maintenance", "In Maintenance"),
                            ("UnknownState", "Unknown State"),
                        ],
                        default="ReadyForOperation",
                        help_text="What the Real estate is ready for",
                        max_length=20,
                    ),
                ),
                (
                    "AssetDescription",
                    models.TextField(help_text="Describes the asset:", max_length=256),
                ),
                (
                    "OwnerOfAsset",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="partners.businesspartner",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RealEstateProperty",
            fields=[
                (
                    "asset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="assets.asset",
                    ),
                ),
                (
                    "RealEstateType",
                    models.CharField(
                        choices=[
                            ("Residential", "Residential"),
                            ("Commercial", "Commercial"),
                            ("Industrial", "Industrial"),
                            ("RawLand", "Raw Land"),
                            ("SpecialUse", "Special Use"),
                        ],
                        default="commercial",
                        help_text="Gross Qualification of the realEstate",
                        max_length=20,
                    ),
                ),
                (
                    "UsageType",
                    models.CharField(
                        choices=[
                            ("SubRentalCluster", "Sub Rental Cluster"),
                            ("SecialUse", "Special Use"),
                        ],
                        default="SubRentalCluster",
                        help_text="Qualifies the nature of the realEstate",
                        max_length=20,
                    ),
                ),
                (
                    "LocationOfPhysicalAsset",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="locations.address",
                    ),
                ),
            ],
            bases=("assets.asset",),
        ),
        migrations.CreateModel(
            name="Box",
            fields=[
                (
                    "asset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="assets.asset",
                    ),
                ),
                (
                    "BoxUnit",
                    models.CharField(
                        help_text="Place of multiple boxes located together",
                        max_length=20,
                    ),
                ),
                (
                    "BoxSubUnit",
                    models.CharField(
                        help_text="Identifies the box uniquely", max_length=20
                    ),
                ),
                (
                    "BoxIntendedVolume",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The overall Volume of the box",
                        max_digits=8,
                    ),
                ),
                (
                    "BoxWidth",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="The width of the Box",
                        max_digits=6,
                    ),
                ),
                (
                    "BoxHeight",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="The height of the Box",
                        max_digits=6,
                    ),
                ),
                (
                    "BoxDepth",
                    models.DecimalField(
                        decimal_places=3, help_text="The depth of the Box", max_digits=6
                    ),
                ),
                (
                    "BelongsTo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assets.realestateproperty",
                    ),
                ),
            ],
            bases=("assets.asset",),
        ),
    ]
