# Generated by Django 4.1.2 on 2023-02-23 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_alter_geographicalunit_geographicalunitcategory_and_more"),
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="AssetId",
            field=models.CharField(
                help_text="Identifies the asset:", max_length=20, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="realestateproperty",
            name="LocationOfPhysicalAsset",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="locations.address",
            ),
        ),
    ]
